version: '3.8'

services:
  wordpress:
    image: wordpress:6.3-php8.1-apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-secure_password_123}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', false);
        define('FORCE_SSL_ADMIN', true);
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress-theme:/var/www/html/wp-content/themes/miner-website
      - ../:/var/www/html/wp-content/themes/miner-website-static
      - ./nginx/ssl:/etc/ssl/certs
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-secure_password_123}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password_123}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/certs
      - ../:/usr/share/nginx/html/static
    depends_on:
      - wordpress
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
    driver: bridge
